### ISSUE TITLE
missing code

### ISSUE THREAD

**Issue by deeksha20049** [GeorgeKyrylenko1998/CoreDataUnitTests#1]
the github repo is empty, the code files are just templates. no code inside them.

**Comment by GeorgeKyrylenko1998** [comment]
@deeksha20049 fixed

**Comment by deeksha20049** [comment]
@GeorgeKyrylenko1998 would by any chance have the the main code too (not just testing part)? i am learning core data and confused with its initialisation and use with swift UI.
Your code might be good reference to implement core data into my app.

**Comment by GeorgeKyrylenko1998** [comment]
@deeksha20049 that's a good point to create article about core data and swiftData usage in swiftUI
